### ISSUE TITLE
Endpoint: Staj Günlüğü Ekle

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#10]

**Comment by huseyindedeyilmaz** [comment]
Endpoint: Staj Günlüğü Eklendi.

**Comment by huseyindedeyilmaz** [comment]
Endpoint: Staj Günlüğü Eklendi.

**Comment by huseyindedeyilmaz** [comment]
Veritabanına msi_internship_journals tablosu eklendi.
Ardından IntershipJournal için controller,service,model,dao,dto klasörlerinde ilgili java dosyaları oluşturuldu.
Endpoint: Staj Günlüğü ekleme fonksiyonu eklendi.
