### ISSUE TITLE
Endpoint: Firma Sorumlusu olarak Kayıt Ol

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#15]

**Comment by iremdehri** [comment]
Firma yetkilisi olarak kayıt eklenmek istenildiğinde:
1. Telefon numarası olarak 10 ya da 11 haneli sayılardan oluşan bir numara girilmeli, buna dair kısıt oluşturulmamış
2. Kayıt esnasında girilen telefon numarası ile sistemde kayıtlı olarak görünen telefon numaraları eşleşmemektedir.
3. Şirket ismi seçiniz diye bir alan var ancak orada çok az sayıda şirket ismi kayıtlı. Tüm şirketleri oraya listelemek zor olacağı için kayıt esnasında şirket isminin manuel olarak girilmesi daha rahat olabilir bence.

**Comment by ykartal** [comment]
> Firma yetkilisi olarak kayıt eklenmek istenildiğinde:
> 
> 1. Telefon numarası olarak 10 ya da 11 haneli sayılardan oluşan bir numara girilmeli, buna dair kısıt oluşturulmamış
> 2. Kayıt esnasında girilen telefon numarası ile sistemde kayıtlı olarak görünen telefon numaraları eşleşmemektedir.
> 3. Şirket ismi seçiniz diye bir alan var ancak orada çok az sayıda şirket ismi kayıtlı. Tüm şirketleri oraya listelemek zor olacağı için kayıt esnasında şirket isminin manuel olarak girilmesi daha rahat olabilir bence.

Bunların her birini farklı talep olarak açıp bu talebi kapatabiliriz. @iremdehri

**Comment by HakanDalkiran** [comment]
Firma yetkilisi olarak kayıt eklenildiğinde yapılabilecek olan iyileştirmeler için görev talebi açılmış gerekli düzenlemeler yapılmıştır
