### ISSUE TITLE
Endpoint: Fakülte Sorumlusu Güncelle

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#17]

**Comment by ahmthlmzn** [comment]
Grup 5 olarak aldık.

**Comment by iremkvkpnr** [comment]
Fakülte sorumlusu istenilen şekilde güncelleniyor fakat güncelleme kısmında fakülte sorumlusu id zaten kullanılan bir id ye son kullanıcı tarafından atanabiliyor. Faculty_supervisor tablosundaki supervisor_no unique bir değer mi olmalı, eğer öyleyse buraya bir kısıtlama getirilmeli.

**Comment by ykartal** [comment]
> Fakülte sorumlusu istenilen şekilde güncelleniyor fakat güncelleme kısmında fakülte sorumlusu id zaten kullanılan bir id ye son kullanıcı tarafından atanabiliyor. Faculty_supervisor tablosundaki supervisor_no unique bir değer mi olmalı, eğer öyleyse buraya bir kısıtlama getirilmeli.

1. Güncelleme ekranında ID kesinlikle yer almamalı. 
2. Supervisor_no aslında sicil_no ve bu şekilde evet benzersiz(unique) bir değer. Kullanıcı kendi değiştiremez ama admin değiştirebilir.

**Comment by iremkvkpnr** [comment]
> > Fakülte sorumlusu istenilen şekilde güncelleniyor fakat güncelleme kısmında fakülte sorumlusu id zaten kullanılan bir id ye son kullanıcı tarafından atanabiliyor. Faculty_supervisor tablosundaki supervisor_no unique bir değer mi olmalı, eğer öyleyse buraya bir kısıtlama getirilmeli.
> 
> 1. Güncelleme ekranında ID kesinlikle yer almamalı.
> 2. Supervisor_no aslında sicil_no ve bu şekilde evet benzersiz(unique) bir değer. Kullanıcı kendi değiştiremez ama admin değiştirebilir.

Admin ekranında fakülte sorumlusu id değiştirilebilir olarak kalsın mı o zaman hocam?

**Comment by ykartal** [comment]
> > > Fakülte sorumlusu istenilen şekilde güncelleniyor fakat güncelleme kısmında fakülte sorumlusu id zaten kullanılan bir id ye son kullanıcı tarafından atanabiliyor. Faculty_supervisor tablosundaki supervisor_no unique bir değer mi olmalı, eğer öyleyse buraya bir kısıtlama getirilmeli.
> > 
> > 
> > 
> > 1. Güncelleme ekranında ID kesinlikle yer almamalı.
> > 2. Supervisor_no aslında sicil_no ve bu şekilde evet benzersiz(unique) bir değer. Kullanıcı kendi değiştiremez ama admin değiştirebilir.
> 
> Admin ekranında fakülte sorumlusu id değiştirilebilir olarak kalsın mı o zaman hocam?

Yanlış anlaşılma olmaması adına;
Tablo'da id, name, surname, supervisor_no,..... alanları var.
id alanı kesinlikle kimse tarafından oynanamaz. supervisor_no alanı admin tarafından değiştirilebilir.

**Comment by iremkvkpnr** [comment]
updateFacultySupervisor fonksiyonu gözden geçirildi ve endpointin istenilen şekilde çalıştığı görüldüğü için herhangi bir değişikliğe gerek duyulmadan bu issue kapatıldı.
