### ISSUE TITLE
Endpoint: Öğrenci kayıt ol

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#19]

**Comment by yakubalkis** [comment]
öğrenci kayıt olma endpointi  daha önce yazılmış, StudentController.java dosyasında 86.satırda mapping eklenmiş. Bunun haricinde bi ister yoksa issue'yu kapatacağım.

**Comment by yakubalkis** [comment]
Daha önce bu iş tamamlanmış.
