### ISSUE TITLE
Update user endpoint

### ISSUE THREAD

**Issue by ABDULHANNANAYUBI** [esogu-ceng/internship-management-system#214]

**Comment by Yasin-Gok** [comment]
@ykartal Burada user güncelle diyor fakat tam olarak neyini güncellemem gerek?

**Comment by ykartal** [comment]
kullanıcı yani user tablosunun güncellenmesi için gerekli endpoint/controller oluşturulmuş mu?
Belki de gerek kalmamıştır. Güncelleme işlemleri her kullanıcı tipi için ayrıca yapııyorsa.

**Comment by Yasin-Gok** [comment]
@ykartal Burada kodları inceledim tek tek repo olsun service ya da controller. Hepsi mantıken tamam fakat rastgele postman'de denemek isteyince hiçbir geri dönüş olmuyor acaba farklı bir şey mi yapılması gerek?

**Comment by ykartal** [comment]
Hiç bir geri dönüş olmuyor derken mutlaka 200 403 500 gibi bir dönüş olmalı. 
Ayrıca istendiği şekilde işlemlerini yapıyor mu?

**Comment by Yasin-Gok** [comment]
401 veriyor hocam, çözerim sandım ama olmadı.

**Comment by Yasin-Gok** [comment]
![Image](https://github.com/esogu-ceng/internship-management-system/assets/64281336/ff5d6782-9c29-4cae-ab71-2d582fc3488d)



![Image](https://github.com/esogu-ceng/internship-management-system/assets/64281336/8c9e6364-8139-44a3-bc10-3886648bed8e)


Yani bu durumda bir şey yazması gerekmez mi acaba?

**Comment by ykartal** [comment]
e-posta bilgilerinin neden buraya yazıyorsun ki? Burada bir yanlış anlaşılma var.

**Comment by Yasin-Gok** [comment]
> e-posta bilgilerinin neden buraya yazıyorsun ki? Burada bir yanlış anlaşılma var.

Onu yazmadan 401 veriyordu, portu 8080 de 3000 de yazarak yaptım. Kod mantıken doğru ama test edemiyorum. Ne yapmam lazım?

**Comment by ykartal** [comment]
username ve password olarak veritabanındaki bilgileri kullanmalısın.

**Comment by Yasin-Gok** [comment]
> username ve password olarak veritabanındaki bilgileri kullanmalısın.

![image](https://github.com/esogu-ceng/internship-management-system/assets/64281336/e240efb0-86e9-42ac-a91b-99fbf0e9aae3)
Mesela burdaki gibi olması gerekmiyor mu? Şifreyi hash'li halini de girdim bunu da girdim yine aynı. Anlamadım.

**Comment by ykartal** [comment]
sunucu tarafında logu takip etmelisin ya da debug ile tespit edebilirsin.

**Comment by Yasin-Gok** [comment]
Tüm sistem bozuldu, tekrar sildim yükledim düzenlerken 5. ve 6. api sıkıntısız çalışıyor fakat diğerlerinde bir username farklılığı var gibi. Yani bir tabloda bulunması gerekirken yok gibi. 
Hata bu: 2024-04-11 23:56:22.280  WARN 10748 --- [nio-8080-exec-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.data.mapping.PropertyReferenceException: No property 'username' found for type 'User'] 
![image](https://github.com/esogu-ceng/internship-management-system/assets/64281336/2b1b0949-9944-4396-9889-b1b6f7d09a6d)

Bu durumda model klasöründeki bu User.Java kısmı mı hatalı yoksa böyle username olmadan mı olması gerekiyor? @ykartal

**Comment by ykartal** [comment]
username User tablosundan kaldırıldı. Bununla ilgili db-scripts/imsdb1.sql dosyasını çalıştırmanız gerektiğiyle ilgili bir duyuru yapılmıştı diye hatırlıyorum. @esogu-ceng/esogu-ceng-24spring

**Comment by Yasin-Gok** [comment]
> username User tablosundan kaldırıldı. Bununla ilgili db-scripts/imsdb1.sql dosyasını çalıştırmanız gerektiğiyle ilgili bir duyuru yapılmıştı diye hatırlıyorum. @esogu-ceng/esogu-ceng-24spring

Tamamdır o şekilde değişince bir sıkıntı yok, bu kullanıcı güncelleme api fonksiyonunda language değerini değiştirmemiz bekleniyor mu yoksa onu yapmayalım mı?

**Comment by Yasin-Gok** [comment]
![image](https://github.com/esogu-ceng/internship-management-system/assets/64281336/1dbaf3aa-a967-4534-b88e-5d05457f26f7)
Yani bu olsun mu olmasın mı?

**Comment by ykartal** [comment]
Veritabanında bir dil tablosu varsa ilişkili o tablodaki dil listesinden seçim yaptırılarak güncellenmesi sağlanabilir. Ama sadece 1 değeri atanmış ve bir anlamı yoksa şimdilik dokunmayabilirsiniz.
