### ISSUE TITLE
CompanySupervisor silindiğinde ona bağlı User silinmiyor. Bu kısmın düzenlenmesi gerekiyor.

### ISSUE THREAD

**Issue by yunusakyol5** [esogu-ceng/internship-management-system#246]

**Comment by ykartal** [comment]
User doğrudan silinmemeli, belli bir kontrol mekanizması ile gerekiyorsa pasif edilmeli. Ancak ilişkili hiç bir veri yoksa silinebilir.

**Comment by yunusakyol5** [comment]
Hocam sanırım companySupervisor silindiği zaman kalan user'ın hiçbir yetkisi ve diğer kısımlara etkisi olmuyor. Bu durumda silinmesi doğru olur diye düşünmüştüm. Yanlış mı düşünüyorum veya atladığım bir nokta var mı? @ykartal

**Comment by ykartal** [comment]
belli olmaz; İlişkili olduğu veri vs varsa kontroller yapılmalı. Bu bir talep sadece not düşüyoruz ileride geliştirici doğrudan silip geçmesin diye.
