### ISSUE TITLE
Endpoint: Öğrenci Ara (Ad-soyad-no ile)

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#27]

**Comment by ahmetoozcan** [comment]
Endpoint çalışmakta, client üzerinde arama olmadığı için url üzerinden test edildi.

Javadoc commentleri eklendi.

![Screenshot 2024-03-20 195428](https://github.com/esogu-ceng/internship-management-system/assets/93215375/ba570cfa-a18c-4572-bbda-e96255734973)
![Screenshot 2024-03-20 195345](https://github.com/esogu-ceng/internship-management-system/assets/93215375/d56ea9ec-d661-4a3e-91c8-768072f4d8ec)
![Screenshot 2024-03-20 195406](https://github.com/esogu-ceng/internship-management-system/assets/93215375/9c02c488-bf48-46f8-a0e1-f57a90068e97)
