### ISSUE TITLE
Sayfa alt bilgilerinde yer alan ...........hazırlanan tüm materyaller .... ibaresini daha anlamlı bir ibare ile değiştirelim. 

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#339]
Ders adı geçmesin.
Osmangazi Üniversitesi Bilgisayuar Müh. adı geçsin.
Öğrencilerin desteği ile geliştirildiği biglisini paylaşalım. Sürüm bilgisi / yıl bilgisi verelim. (Şimdilik v1.0 / 2024)
gibi ....

**Comment by ansanami** [comment]
@ykartal 

© Osmangazi Üniversitesi Bilgisayar Mühendisliği öğrencileri tarafından hazırlanmıştır. Tüm hakları Osmangazi Üniversitesi Bilgisayar Mühendisliği'ne aittir. Tag: v1.0

şeklinde iyi mi hocam?
