### ISSUE TITLE
Admin modülünde tabloda öğrenci silme sırasında kullanıcıdan evet/hayır şeklinde onay alınması gerekir. 

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#345]

**Comment by vahdetaltundas** [comment]
Anladım hocam bu işlem frontend tarafında Popup şeklindemi olucak yoksa backend kısmındamı bi geliştirme yapmam gerekiyor?

**Comment by ykartal** [comment]
> Anladım hocam bu işlem frontend tarafında Popup şeklindemi olucak yoksa backend kısmındamı bi geliştirme yapmam gerekiyor?

frontend tarafında olmalı.

**Comment by ykartal** [comment]
Kapatıldı ama nasıl yapıldı? PR vs göremedik @vahdetaltundas
