### ISSUE TITLE
Admin modülünde şirket sorumlusu ekleme işlemi sırasında şirket bilgileri de alınarak şirketin de oluşturulması sağlanmalı.

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#349]
Şirketleri comboboxtan seçmek yerine şirket adı girilirken backend taraftan girilen karakterler ile şirketler getirilip listelenip seçtirilmesi ve bu bilgiler ile şirket diğer alanları doldurulması sağlanabilir. Eğer bulunan bir şirket yoksa girilen isim ve bilgiler ile kayıt aşamasında şirket oluşturulabilir.

**Comment by ergunaltindag** [comment]
Hocam teyit etmek için soruyorum backend tarafında bi controller ile isme göre girilen şirketleri getirecek  bir endpoint ve eğer o isimde bir şirket yoksa girlilen verilerle yeni bir şirket kaydedecek bir endpoint yazmam isteniyor bu aşamadan sonra frontend tarafında değişiklik sağlamalıyım yoksa sadece şuan backend tarafınımı yazmam gerekli

**Comment by ykartal** [comment]
Her iki tarafta da gerekli geliştirmeler yapılmalı.
