### ISSUE TITLE
Fakülte Sorumlusu modülünde firma ekranlarında düzenleme

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#366]
Firma ekranlarının tasarımı admin ekranlarındaki ile benzer olarak yeniden tasarlansın.
Pagesize ve sort by bilgilri buradan kaldırılsın.

**Comment by yakubalkis** [comment]
İlgili sorun https://github.com/esogu-ceng/internship-management-system/pull/451 merge edilerek çözüldü.
