### ISSUE TITLE
Firma Sorumlusu staj günüklerini tek tek ya da toplu olarak onaylayabilmeli. 

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#371]
Onaylamak için sta günlüklerini görüntüleyebilmeli. Tek sayfada bir kere tüm günlere ait staj bilgilerini görmesi pratik olacaktır.

Not: Mevcutta modal/pop-up ile açılmış. Tam sayfa görüntülenmesi ve scroll ile aşağı doğru uzayarak tüm günlük yazılarının gösterilmesi uygun olacaktır. En alta ve an yukarıya toplu onay düğmeleri konabilir. Her günlüğün yanında da tek tek onay düğmesi olmalıdır.

**Comment by huseyindedeyilmaz** [comment]
-internshipRow.tsx: InternshipJournal için gerekli modal ve fonksiyonlar eklendi.
-InternshipJournalType.tsx: InternshipJournal için type oluşturuldu.
-InternshipJournal.tsx: Modal için gerekli dosya oluşturuldu ve içi dolduruldu.

-internshipJournalController: İster için gerekli fonksiyonlar eklendi.
-internshipJournalService:  İster için gerekli fonksiyonlar eklendi.

![1](https://github.com/esogu-ceng/internship-management-system/assets/101169674/3acb319d-fbb7-413a-aa36-fbfacc73eeff)
-Staj günlükleri için simge yalnızca kabul olan stajlar için gözükmekte.

![2](https://github.com/esogu-ceng/internship-management-system/assets/101169674/af26c4b8-d8e7-4ef1-800a-d389991b1fc9)
-Staj günlükleri liste halinde kullanıcıya verilmekte.Her günlük için onay butonu bulunmakta.Ek olarak hepsini onaylamak için bir buton bulunmakta.

![3](https://github.com/esogu-ceng/internship-management-system/assets/101169674/f51ebe15-9a34-44a4-8f28-75d70cfc0239)
-Günlük onayından sonra kullanıcıyı bilgilendirmek için notification eklendi.

![4](https://github.com/esogu-ceng/internship-management-system/assets/101169674/642544b1-2cd2-47ae-b015-a9af3842d24e)
-Tüm günlüklerin onayından sonra kullanıcıyı bilgilendirmek için notification eklendi.
