### ISSUE TITLE
Fakülte sorumlusu firma tarafından değerlendirmesi de yapılan öğrencilerin tüm girdilerini inceleyerek stajı STAJ TAMAMLANDI işaretleyebilmeli. 

### ISSUE THREAD

**Issue by ykartal** [esogu-ceng/internship-management-system#377]
@362 staj durumlarını gösteren maddeler yer almaktadır

**Comment by vitalvirtue** [comment]
#362 nolu issue mergelenmediği için enumlar güncel değil, ancak, issue commentleri incelendiği zaman TAMAMLANDI olarak SUCCESS enum'u yazıldığı görülüyor. Bu issue'daki düzeltmelere göre düzeltmeleri yapıyorum.

**Comment by vitalvirtue** [comment]
![Ekran görüntüsü 2024-04-17 010203](https://github.com/esogu-ceng/internship-management-system/assets/68844223/e4514650-5ac0-437f-be79-0dc6468d522f)

Test Build Success

**Comment by vitalvirtue** [comment]
Fakülte sorumlusu firma tarafından değerlendirmesi de yapılan öğrencilerin kontrolü eklendi. Başarılı şekilde test edildi

![Ekran görüntüsü 2024-04-17 030435](https://github.com/esogu-ceng/internship-management-system/assets/68844223/30d6c3a2-4d8f-4592-8c87-0c1c992b9402)
